apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "{{ include "kstatus.fullname" . }}-ui"
spec:
  minAvailable: {{ .Values.minAvailable }}
  selector:
    matchLabels:
      app: "{{ include "kstatus.name" . }}-ui"
      release: {{ .Release.Name }}